# Generated by Django 3.2.3 on 2021-05-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade_type',
            new_name='grade_level',
        ),
    ]
